'use strict'

const yenv = require('yenv')
const env = yenv('./env.yml', {
	env: 'default'
})
const advito = require('knex')({
	client: 'pg',
	connection: {
		user: process.env.DB_USER ? process.env.DB_USER : env.DB_USER,
		host: process.env.DB_HOST ? process.env.DB_HOST : env.DB_HOST,
		database: process.env.DB_ADVITO ? process.env.DB_ADVITO : env.DB_ADVITO,
		password: process.env.DB_PASSWORD
			? process.env.DB_PASSWORD
			: env.DB_PASSWORD
	}
})

module.exports.loadEnhancedQc = async (event) => {
	try {
		const { jobIngestionHotels } = event
		if (!jobIngestionHotels || jobIngestionHotels.length === 0)
			throw Error('Job ingestion not found')
		await Promise.all(
			jobIngestionHotels.map((hotel) =>
				advito.raw(
					`select * from load_for_sourcing_dpm(${hotel.jobIngestionId}, ${hotel.clientId}, ${hotel.year}, ${hotel.month}, '${hotel.type}')`
				)
			)
		)
		return true
	} catch (e) {
		console.log(e)
		throw Error('Loading enhanced QC failed')
	}
}

// module.exports.ingestHotelTemplate({
// 	jobIngestionId: 18758,
// 	start: 0,
// 	end: 15,
// 	final: true,
// 	data: `[
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-09-30T00:00:00.000Z",
// 					"check-out date": "2019-10-04T00:00:00.000Z",
// 					"number of nights": 4,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 404,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-09-30T00:00:00.000Z",
// 					"check-out date": "2019-10-03T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 303,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-09-30T00:00:00.000Z",
// 					"check-out date": "2019-10-03T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 303,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-09-30T00:00:00.000Z",
// 					"check-out date": "2019-10-04T00:00:00.000Z",
// 					"number of nights": 4,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 404,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-15T00:00:00.000Z",
// 					"check-out date": "2019-10-18T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 303,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-16T00:00:00.000Z",
// 					"check-out date": "2019-10-17T00:00:00.000Z",
// 					"number of nights": 1,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 101,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-27T00:00:00.000Z",
// 					"check-out date": "2019-10-29T00:00:00.000Z",
// 					"number of nights": 2,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 202,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Courtyard",
// 					"brand code": "CY",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Courtyard Tyler Marriott",
// 					"hotel name alternate": null,
// 					"address line 1": "7424 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035094411,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-28T00:00:00.000Z",
// 					"check-out date": "2019-10-29T00:00:00.000Z",
// 					"number of nights": 1,
// 					"number of rooms": 1,
// 					"room rate": 101,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 101,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Holiday Inns",
// 					"brand code": "HI",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Holiday Inn South Broadway",
// 					"hotel name alternate": null,
// 					"address line 1": "5701 South Broadway Avenue",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75703,
// 					"phone number": 19035615800,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-16T00:00:00.000Z",
// 					"check-out date": "2019-10-17T00:00:00.000Z",
// 					"number of nights": 1,
// 					"number of rooms": 1,
// 					"room rate": 85.28,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 85.28,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Holiday Inns",
// 					"brand code": "HI",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Holiday Inn Express Suites S.E.",
// 					"hotel name alternate": null,
// 					"address line 1": "2421 Ese Loop323",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035660600,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-09-30T00:00:00.000Z",
// 					"check-out date": "2019-10-03T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 81.18,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 243.54,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-17T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 327,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-17T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 327,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-17T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 327,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-17T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 327,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-07T00:00:00.000Z",
// 					"check-out date": "2019-10-10T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 327,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-18T00:00:00.000Z",
// 					"number of nights": 4,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 436,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-18T00:00:00.000Z",
// 					"number of nights": 4,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 436,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-10-14T00:00:00.000Z",
// 					"check-out date": "2019-10-18T00:00:00.000Z",
// 					"number of nights": 4,
// 					"number of rooms": 1,
// 					"room rate": 109,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 436,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}
// 			,
// 			{
// 					"chain name": "Homewood Suites",
// 					"brand code": "HG",
// 					"brand name": null,
// 					"internal hotel code": null,
// 					"lanyon id": null,
// 					"sabre property id": null,
// 					"apollo property id": null,
// 					"worldspan property id": null,
// 					"amadeus property id": null,
// 					"hrs id": null,
// 					"hotel name": "Homewood Suites Tyler",
// 					"hotel name alternate": null,
// 					"address line 1": "3104 Golden Road",
// 					"address line 2": null,
// 					"city name": "Tyler",
// 					"city latitude": null,
// 					"city longitude": null,
// 					"state code": "TX",
// 					"country name": "United States",
// 					"country code": "US",
// 					"zip or postal code": 75701,
// 					"phone number": 19035937880,
// 					"hotel latitude": null,
// 					"hotel longitude": null,
// 					"start date": "2019-10-01T00:00:00.000Z",
// 					"end date": "2019-10-31T00:00:00.000Z",
// 					"check-in date": "2019-09-30T00:00:00.000Z",
// 					"check-out date": "2019-10-03T00:00:00.000Z",
// 					"number of nights": 3,
// 					"number of rooms": 1,
// 					"room rate": 107.1,
// 					"transaction currency": "USD",
// 					"report currency": "USD",
// 					"currency coversion rate": null,
// 					"room spend": 321.3,
// 					"fees and taxes": null,
// 					"breakfast": null,
// 					"wifi": null,
// 					"parking": null,
// 					"in-room dining": null,
// 					"f&b spend": null,
// 					"entertainment": null,
// 					"transportation": null,
// 					"other spend": null,
// 					"total hotel spend": null
// 			}]`
// })
