'use strict'

const yenv = require('yenv')
const env = yenv('./env.yml', {
	env: 'default'
})
const advito = require('knex')({
	client: 'pg',
	connection: {
		user: process.env.DB_USER ? process.env.DB_USER : env.DB_USER,
		host: process.env.DB_HOST ? process.env.DB_HOST : env.DB_HOST,
		database: process.env.DB_ADVITO ? process.env.DB_ADVITO : env.DB_ADVITO,
		password: process.env.DB_PASSWORD
			? process.env.DB_PASSWORD
			: env.DB_PASSWORD
	}
})

module.exports.ingestHotelTemplate = async (event) => {
	try {
		const { jobIngestionId, data, start, end, final } = event
		if (!jobIngestionId) throw Error('Job ingestion not found')
		const jobIngestion = await advito('job_ingestion')
			.where('id', jobIngestionId)
			.first()
		if (!jobIngestionId) throw Error('Job ingestion not found')
		const {
			data_start_date: dataStartDate,
			data_end_date: dataEndDate
		} = jobIngestion
		const date1 = new Date(dataStartDate)
		const date2 = new Date(dataEndDate)
		const midpoint = new Date((date1.getTime() + date2.getTime()) / 2)
		console.log('midpoint date: ', midpoint.toLocaleDateString())
		const columnList = await advito('advito_application_template_column as tc')
			.select('tc.column_name', 'tc.stage_column_name', 'i.file_name')
			.leftJoin(
				'advito_application_template_source as ts',
				'ts.advito_application_template_id',
				'tc.advito_application_template_id'
			)
			.leftJoin(
				'job_ingestion as i',
				'i.advito_application_template_source_id',
				'ts.id'
			)
			.where('i.id', jobIngestionId)
		const { rows: currencyList } = await advito.raw(`
		SELECT	currency_code_to, conversion_rate_reverse, conversion_date
			FROM		currency_conversion cc
			WHERE		id IN (SELECT id FROM currency_conversion WHERE currency_code_to = cc.currency_code_to AND currency_code_from = 'USD' AND conversion_date <= '${midpoint.toLocaleDateString()}' ORDER BY conversion_date DESC LIMIT 1)
			ORDER BY currency_code_to
		`)
		const parsedData = JSON.parse(data)
		const insertArray = parsedData.map((json) => {
			const returnObj = {
				job_ingestion_id: jobIngestionId
			}
			Object.keys(json).forEach((key) => {
				const column = columnList.find(
					(c) => c.column_name.toLowerCase() === key.trim().toLowerCase()
				)
				if (column !== undefined) {
					if (column.stage_column_name === 'room_spend') {
						let currencyCode = json['source currency code']
							? json['source currency code'].toLowerCase()
							: json['report currency']
							? json['report currency'].toLowerCase()
							: ''
						const currency = currencyList.find(
							(c) => c.currency_code_to.toLowerCase() === currencyCode
						)
						returnObj['room_spend_usd'] = currency
							? String(+json['room spend'] * +currency.conversion_rate_reverse)
							: String(+json['room spend'])
					}
					returnObj[column.stage_column_name] = String(json[key]).trim()
				}
			})
			return returnObj
		})
		console.log(`Inserting rows [${start}:${end}] into db`)
		console.log('insert array: ', insertArray)
		console.log('data: ', data)
		const result = await advito('stage_activity_hotel').insert(insertArray)
		if (final) {
			console.log(`Expected to insert ${end - start} rows.`)
			console.log(`Data length is: ${parsedData.length}.`)
			console.log(`Insert length is: ${insertArray.length}.`)
			console.log(`Inserted ${result.rowCount} rows into DB.`)
			console.log('Inserted into job: ', jobIngestionId)
			await advito('job_ingestion')
				.update({
					is_complete: true,
					job_status: 'ingested',
					job_note: `Ingestion Date: ${new Date().toLocaleString()}`
				})
				.where('id', jobIngestionId)
		}
		return `Insert ${jobIngestionId} into successful`
	} catch (e) {
		console.log(e)
		await advito('job_ingestion')
			.update({
				is_complete: true,
				job_status: 'error',
				job_note: `Error with inserting rows: ${e.message}`
			})
			.where('id', event.jobIngestionId)
	}
}

// module.exports.ingestHotelTemplate({
// 	jobIngestionId: 990,
// 	start: 7050,
// 	end: 7161,
// 	final: true,
// 	data: `[
// 		{
// 				"chain name": "Radisson Hotels & Resorts",
// 				"brand code": "RD",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Radisson Blu Hotel Chennai",
// 				"hotel name alternate": null,
// 				"address line 1": "531 G S T Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 600043,
// 				"phone number": 914422310101,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-14T00:00:00.000Z",
// 				"check-out date": "2019-10-16T00:00:00.000Z",
// 				"number of nights": 2,
// 				"number of rooms": 1,
// 				"room rate": 77.88,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 155.76,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Travelclick",
// 				"brand code": "WV",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hablis",
// 				"hotel name alternate": null,
// 				"address line 1": "19 G S T Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 600032,
// 				"phone number": 914422334000,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-22T00:00:00.000Z",
// 				"check-out date": "2019-10-23T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 56.38,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 56.38,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Travelclick",
// 				"brand code": "WV",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hablis",
// 				"hotel name alternate": null,
// 				"address line 1": "19 G S T Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 600032,
// 				"phone number": 914422334000,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-22T00:00:00.000Z",
// 				"check-out date": "2019-10-23T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 56.62,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 56.62,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Travelclick",
// 				"brand code": "WV",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "The Residency Towers",
// 				"hotel name alternate": null,
// 				"address line 1": "115 Sir Thyagaraya Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 600017,
// 				"phone number": 914428156363,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-16T00:00:00.000Z",
// 				"check-out date": "2019-10-18T00:00:00.000Z",
// 				"number of nights": 2,
// 				"number of rooms": 1,
// 				"room rate": 70.17,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 140.33,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Pegasus Solutions",
// 				"brand code": "UI",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Fortune Select Grand Chennai",
// 				"hotel name alternate": null,
// 				"address line 1": "1 Gst Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 603204,
// 				"phone number": 914467414243,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-09T00:00:00.000Z",
// 				"check-out date": "2019-10-10T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 70.89,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 70.89,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Pegasus Solutions",
// 				"brand code": "UI",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Fortune Select Grand Chennai",
// 				"hotel name alternate": null,
// 				"address line 1": "1 Gst Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 603204,
// 				"phone number": 914467414243,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-10T00:00:00.000Z",
// 				"check-out date": "2019-10-11T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 70.51,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 70.51,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Quality Inns",
// 				"brand code": "QI",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Quality Inn Airport",
// 				"hotel name alternate": null,
// 				"address line 1": "5 Old Station Road",
// 				"address line 2": null,
// 				"city name": "Chennai",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": null,
// 				"phone number": 914477122000,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-16T00:00:00.000Z",
// 				"check-out date": "2019-10-19T00:00:00.000Z",
// 				"number of nights": 3,
// 				"number of rooms": 1,
// 				"room rate": 47.57,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 142.72,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Hilton Garden Inns",
// 				"brand code": "GI",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hgi Westchester Do",
// 				"hotel name alternate": null,
// 				"address line 1": "201 Ogden Avenue",
// 				"address line 2": null,
// 				"city name": "White Plains",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": "NY",
// 				"country name": "United States",
// 				"country code": "US",
// 				"zip or postal code": 10522,
// 				"phone number": 9145914300,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-28T00:00:00.000Z",
// 				"check-out date": "2019-10-30T00:00:00.000Z",
// 				"number of nights": 2,
// 				"number of rooms": 1,
// 				"room rate": 143.1,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 286.2,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Hilton Garden Inns",
// 				"brand code": "GI",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hgi Westchester Do",
// 				"hotel name alternate": null,
// 				"address line 1": "201 Ogden Avenue",
// 				"address line 2": null,
// 				"city name": "White Plains",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": "NY",
// 				"country name": "United States",
// 				"country code": "US",
// 				"zip or postal code": 10522,
// 				"phone number": 9145914300,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-01T00:00:00.000Z",
// 				"check-out date": "2019-10-02T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 152.1,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 152.1,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Staybridge Suites",
// 				"brand code": "YZ",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Embassy Stes Sac Riverfront",
// 				"hotel name alternate": null,
// 				"address line 1": "Cl/ Capital Mall 100",
// 				"address line 2": null,
// 				"city name": "Oakland",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": "CA",
// 				"country name": "United States",
// 				"country code": "US",
// 				"zip or postal code": 95814,
// 				"phone number": 9163265001,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-01T00:00:00.000Z",
// 				"check-out date": "2019-10-02T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 166.35,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 166.35,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Independent",
// 				"brand code": "XX",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Nocci Business Park",
// 				"hotel name alternate": null,
// 				"address line 1": "Bampada Near Birla Tyres",
// 				"address line 2": null,
// 				"city name": "Kolkata",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": null,
// 				"phone number": 916782255966,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-09T00:00:00.000Z",
// 				"check-out date": "2019-10-16T00:00:00.000Z",
// 				"number of nights": 7,
// 				"number of rooms": 1,
// 				"room rate": 48.09,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 336.61,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Sabre Hospitality",
// 				"brand code": "YX",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Wow Hotel Indore",
// 				"hotel name alternate": null,
// 				"address line 1": "Plot 106 Scheme 54",
// 				"address line 2": null,
// 				"city name": "Indore",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": null,
// 				"phone number": 917316711111,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-17T00:00:00.000Z",
// 				"check-out date": "2019-10-18T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 58.9,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 58.9,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Sabre Hospitality",
// 				"brand code": "YX",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Wow Hotel Indore",
// 				"hotel name alternate": null,
// 				"address line 1": "Plot 106 Scheme 54",
// 				"address line 2": null,
// 				"city name": "Indore",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": null,
// 				"phone number": 917316711111,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-17T00:00:00.000Z",
// 				"check-out date": "2019-10-18T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 63.1,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 63.1,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Hyatt Hotels",
// 				"brand code": "HY",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hyatt Regency Ahmedabad",
// 				"hotel name alternate": null,
// 				"address line 1": 17,
// 				"address line 2": null,
// 				"city name": "Ahmedabad",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": "GUJARA",
// 				"phone number": 917940171234,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-16T00:00:00.000Z",
// 				"check-out date": "2019-10-18T00:00:00.000Z",
// 				"number of nights": 2,
// 				"number of rooms": 1,
// 				"room rate": 70.11,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 140.23,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Hyatt Hotels",
// 				"brand code": "HY",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hyatt Regency Ahmedabad",
// 				"hotel name alternate": null,
// 				"address line 1": "17a Ashram Road",
// 				"address line 2": null,
// 				"city name": "Ahmedabad",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 380009,
// 				"phone number": 917940171234,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-22T00:00:00.000Z",
// 				"check-out date": "2019-10-23T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 85.63,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 85.63,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}
// 		,
// 		{
// 				"chain name": "Hyatt Hotels",
// 				"brand code": "HY",
// 				"brand name": null,
// 				"internal hotel code": null,
// 				"lanyon id": null,
// 				"sabre property id": null,
// 				"apollo property id": null,
// 				"worldspan property id": null,
// 				"amadeus property id": null,
// 				"hrs id": null,
// 				"hotel name": "Hyatt Regency Ahmedabad",
// 				"hotel name alternate": null,
// 				"address line 1": "17a Ashram Road",
// 				"address line 2": null,
// 				"city name": "Ahmedabad",
// 				"city latitude": null,
// 				"city longitude": null,
// 				"state code": null,
// 				"country name": "India",
// 				"country code": "IN",
// 				"zip or postal code": 380009,
// 				"phone number": 917940171234,
// 				"hotel latitude": null,
// 				"hotel longitude": null,
// 				"start date": "2019-10-01T00:00:00.000Z",
// 				"end date": "2019-10-31T00:00:00.000Z",
// 				"check-in date": "2019-10-23T00:00:00.000Z",
// 				"check-out date": "2019-10-24T00:00:00.000Z",
// 				"number of nights": 1,
// 				"number of rooms": 1,
// 				"room rate": 70.11,
// 				"transaction currency": "USD",
// 				"report currency": "USD",
// 				"currency conversion rate": null,
// 				"room spend": 70.11,
// 				"fees and taxes": null,
// 				"breakfast": null,
// 				"wifi": null,
// 				"parking": null,
// 				"in-room dining": null,
// 				"f&b spend": null,
// 				"entertainment": null,
// 				"transportation": null,
// 				"other spend": null,
// 				"total hotel spend": null
// 		}]`
// })
